### PR TITLE
fix: Homepage updated #1

### PR DESCRIPTION
**Pull request by kk7188048**
### Description

This pull request updates Homepage with issue no. #1 

### Changes Made

- Updated Homepage.tsx in component section

image

### CODE REVIEW

**Comment by kk7188048** [comment]
If anymore changes required or any other issue. Please let me know.
Thanks

**Comment by ahaandesai27** [comment]
image Make the homepage similar to this color scheme. Make the background black, and add more changes if you like.

Also add a carousel of (newly added) games, something similar to this:
image

Thank you for your interest in this issue.

**Comment by kk7188048** [comment]
OK let me see this

**Comment by kk7188048** [comment]
image
I have made the changes

**Comment by ahaandesai27** [comment]
Alright, will review and merge later

**Comment by ahaandesai27** [comment]
Thank you for your contribution,

**Comment by ahaandesai27** [comment]
Can you please delete the Payments.tsx file in the repo, it might have some sensitive info

**Pull request merged**
